### ISSUE TITLE
--prof can have sampling frequency configured

### ISSUE THREAD

**Issue by carera** [slonka/nodejs-production-ready-profiling#1]
Hi mate!

In your README.md you claim that when using `--prof`, the sampling frequency cannot be defined. However `node --v8-options` show that a certain flag is available:
```
  --prof-sampling-interval (Interval for --prof samples (in microseconds).)
        type: int  default: 1000
```

**Comment by slonka** [comment]
Hi :)

Thanks for the update. I was basing it on nodejs docs: https://nodejs.org/api/cli.html#cli_prof here it does not specify that flag.

**Comment by slonka** [comment]
Fixed in master
